version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: ibm_postgres_db
    ports:
      - '5432:5432'
    environment: 
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local